[app]
data_dir = "data"
date_fmt = "%Y-%m-%d %H:%M:%S"
lag_days = 2
leetcode_graphql_url = "https://leetcode.com/graphql"
llm_predictor = "openrouter"
max_recs = 2000
n_api_retries = 3

[parsing]
max_base_offer = 120
max_total_offer = 200
min_base_offer = 2
min_total_offer = 3

[llms]
ollama_model = "llama3.1:8b-instruct-q5_K_M"
openrouter_model = "meta-llama/llama-3.1-8b-instruct:free"
openrouter_req_per_min = 20
openrouter_url = "https://openrouter.ai/api/v1/chat/completions"
vllm_model = "meta-llama/Meta-Llama-3-8B-Instruct"
vllm_url = "http://localhost:8000/v1/completions"
